config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  resources :registered_applications

  devise_for :users

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

   def create
     registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

     if registered_application
       @event = registered_application.events.new(event_params)
         if @event.save
           render json: @event, status: :created
         else
           render json: {errors: @event.errors}, status: :unprocessable_entity
         end
      else
          render json: "Unregistered application", status: :unprocessable_entity
      end
   end

   def preflight
    head 200
   end

   private
   def event_params
     params.require(:event).permit(:name)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)
    @registered_application.user = current_user

      if @registered_application.save
         flash[:notice] = "Application was registered successfully."
         redirect_to @registered_application
       else
         flash.now[:alert] = "Error registering application. Please try again."
         render :new
       end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    @registered_application.assign_attributes(registered_application_params)

      if @registered_application.save
        flash[:notice] = "RegisteredApplication was updated."
        redirect_to @registered_application
      else
        flash.now[:alert] = "Error registering application. Please try again."
        render :edit
      end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])

     if @registered_application.destroy
       flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the registered_application."
       render :show
     end
  end

  private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])

    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
      redirect_to welcome_index_path
    else
      flash[:error] = "Error deleting application. Please try again."

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
      <% if user_signed_in? %>
         Signed in as: <strong><%= current_user.email %></strong> |
         <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
         <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
         <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
      </div>
      <% end %>
    </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for @registered_application do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter item name" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
      <%= f.text_field :url %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/registered_applications/edit.html.erb
<div class="page-header">
  <h1>Edit Registered Applications</h1>
</div>

 <div class="row">
   <div class="col-md-8">
     <%= render partial: 'form', locals: { registered_application: @registered_application} %>
   </div>
 </div>

app/views/registered_applications/index.html.erb
<div class="row">
  <h1>All Applications</h1>

  <div class="col-md-4">
      <%= link_to "Register an Application", new_registered_application_path, class: "btn btn-success" %>
  </div>
  <hr>

  <div class='row'>
    <div class='col-md-8'>
     <% @registered_applications.each do |r| %>
       <div class='media'>
         <div class="media-body">
           <h4 class="media-heading">
      	     <%= link_to r.name, r %>
           </h4>
      	   <small><%= r.url %></small>
         </div>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/registered_applications/new.html.erb
<h1>New Registered Application</h1>
<br>
  <%= render partial: 'form', locals: {registered_application: @registered_application} %>

app/views/registered_applications/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div>
        <h3><%= @registered_application.name %></h3>
        <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
      </div>

      <div class="row">
       <h4><%= @registered_application.url %></h4>
       <% @events.each do |name, events| %>
         <h3><%= name %>:</h3>
          <p>Count: <%= events.size %></p>
         <% end %>
      </div>
    </div>

    <div class="col-md-4">
      <%= link_to "Back to index", registered_applications_path, class: 'btn btn-primary' %>
      <%= link_to "Edit", edit_registered_application_path(@registered_application), class: 'btn btn-success' %>
      <%= link_to "Delete", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
    </div>
  </div>

  <%= pie_chart @registered_application.events.group(:name).count %>
<%= line_chart @registered_application.events.group_by_day(:created_at).count %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>